- name: "Install Jupyter notebook using pip"
  pip:
    name: notebook
    executable: pip3

- name: "Install pyspark python module"
  pip:
    name: pyspark
    version: 2.4.5 # ToDo - set spark version in a global config or move this to the spark role
    executable: pip3

- name: install Uber's H3
  pip:
    name: h3
    executable: pip3

- name: Install folium
  pip:
    name: folium
    executable: pip3

- name: "Install python3 kernel"
  shell: python3 -m pip install ipykernel

- name: "Make python3 kernel available"
  shell: python3 -m ipykernel install --user

- include: config.yml

- name: "Start the notebook server"
  shell: "nohup {{ jupyter_home }}/jupyter notebook --no-browser &"
  register: out
  become_user: "{{ jupyter_user }}"

- debug: var=out.stderr_lines
