---

- name: "Register all eventhubs within namespace"
  command: az eventhubs eventhub list --resource-group {{ resource_group }} --namespace-name {{ namespace_item }}
  register: eventhubs_list

- set_fact: eventhubs="{{ eventhubs_list.stdout|from_json }}"

- debug:
    var: eventhubs

- name: "Store eventhub facts in consul"
  include_tasks: azure-eventhub-facts.yml
  with_items: "{{ eventhubs }}"