---
- name: "Install python-consul module"
  pip:
    name: python-consul
    executable: pip3

- name: "Register all deployed eventhubs"
  include_tasks: azure-namespace-facts.yml
  loop: "{{ namespaces.split(',') }}"
  loop_control:
    loop_var: namespace_item

- name: "Store datalake facts"
  include_tasks: azure-datalake-facts.yml

- name: "Store azure service principal ID in Consul"
  consul_kv:
    key: azure/client/id
    value: "{{ azure_client_id }}"

- name: "Store azure service principal secret in Consul"
  consul_kv:
    key: azure/client/secret
    value: "{{ azure_client_secret }}"

- name: "Store azure service principal tenant ID in Consul"
  consul_kv:
    key: azure/tenant/id
    value: "{{ azure_tenant_id }}"
  