---
  - name: "Fetch connection string for each eventhub"
    command: az eventhubs eventhub authorization-rule keys list --resource-group {{ resource_group }} --namespace-name {{ namespace_item }} --eventhub-name {{ item.name }} --name {{ item.name }}-auth-rule
    register: eventhub_key
    no_log: True

  - set_fact:
      eventhub: "{{ eventhub_key.stdout|from_json }}"
    no_log: True

  - name: Debugger
    debug:
      msg: "{{ eventhub }}"

  - name: "Store eventhub topic key name in Consul"
    consul_kv:
      key: eventhub/topic/{{ eventhub.keyName.split('-')[0] }}/keyName
      value: "{{ eventhub.keyName }}"
    #no_log: True

  - name: "Store eventhub topic connection strings in Consul"
    consul_kv:
      key: eventhub/topic/{{ eventhub.keyName.split('-')[0] }}/connectionString
      value: "{{ eventhub.primaryConnectionString }}"
    no_log: True

  - name: "Store eventhub topic primary key in Consul"
    consul_kv:
      key: eventhub/topic/{{ eventhub.keyName.split('-')[0] }}/primaryKey
      value: "{{ eventhub.primaryKey }}"
    no_log: True
