---
- name: "Dowload and install CLI for Debian"
  shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  when: ansible_os_family == 'Debian'

- name: "Dowload Azure CLI for CentOS"
  shell: rpm --import https://packages.microsoft.com/keys/microsoft.asc
  when: ansible_os_family == 'RedHat'

- name: "Create local repo"
  template:
    dest: /etc/yum.repos.d/azure-cli.repo
    src: azure-cli.repo.j2
  when: ansible_os_family == 'RedHat'
  
- name: "Install Azure CLI for CentOS"
  package:
      name: azure-cli

- name: "Add iot hub extension"
  shell: az extension add --name azure-iot
