---
- name: "Check if Azure CLI is installed"
  shell: az --version
  ignore_errors: yes
  register: azure_status

- include: azure-cli-install.yml
  when: azure_status.failed
  tags:
    - azure-cli-install

- include: azure-cli-conf.yml
  tags:
    - azure-cli-conf

- include: azure-deployment-facts.yml