- name: "Install pip3"
  package:
    name: python3-pip
    state: latest

- name: "Upgrade pip3"
  command: pip3 install --upgrade pip

- name: "Add EPEL repo for CentOS"
  package:
      name: epel-release
  when: ansible_os_family == 'RedHat'

- name: "Install pip2"
  package:
    name: python-pip
    state: latest

- name: "Upgrade pip2"
  command: pip install --upgrade pip
