- name: set spark installation path fact
  set_fact: spark_installation_dir=spark-{{ spark.version }}-bin-{{ spark.hadoop_version }}

- name: define installation directory
  set_fact: install_dir="{{ spark.install_dir }}/{{ spark_installation_dir }}"

- name: start-cluster utility
  template: src="spark-cluster.sh.j2" dest="{{ install_dir }}/bin/spark-cluster.sh" mode=0744
  when: inventory_hostname in groups[target_server_group]
  become: yes
